### ISSUE TITLE
Deletion of allocated pointer

### ISSUE THREAD

**Issue by NicolBolas** [AwokenGraphics/diamond-gl#1]
`base::allocate` allocates memory dynamically. That memory never gets deleted by `base`'s destructor. Nor do any classes that derive from `base`. Or at least, not `shader` nor `program` nor `program_pipeline`.

The destructor of `base` ought to deallocate the memory, since `base` is the class that allocated it and manages it.

**Comment by capitalknew** [comment]
I tried to solve this problem.

**Comment by NicolBolas** [comment]
Putting `deallocate` calls in every derived class's destructor is a rather poor solution, compared to putting it in `base`'s destructor where it belongs. If a class allocates memory, then it is that class's responsibility to deallocate it.

**Comment by capitalknew** [comment]
C++ really bad language. I cannot create multiple class and multi-bind correctly. C++ cannot conversion class arrays to multi-bindable intrinsics.
