### ISSUE TITLE
Rvalue references don't work that way.

### ISSUE THREAD

**Issue by NicolBolas** [AwokenGraphics/diamond-gl#2]
Consider this code:

````
uniform&& get_uniform(GLuint location) const {
  return uniform((GLuint)thisref, location);
}
````

This returns a reference to a temporary. A temporary which will be destroyed *immediately* upon the exit from this function. So the returned reference will be a reference to a destroyed object.

And therefore, any use of that reference will be undefined behavior.

You want to return a value, not a reference:

````
uniform get_uniform(GLuint location) const {
  return uniform((GLuint)thisref, location);
}
````

**Comment by capitalknew** [comment]
I planned to rewrite library tomorrow. I have so much code bloat.
